SELECT AGE_RANGE, LDGS_ADDR, VISIT_CNT
FROM (
		SELECT AGE_RANGE, LDGS_ADDR, COUNT(*) AS VISIT_CNT,
		ROW_NUMBER() OVER (PARTITION BY AGE_RANGE ORDER BY COUNT(*) DESC) AS ROW_NUM
		FROM TRAVEL_DATA
		WHERE AGE_RANGE IN ('20대', '30대', '40대', '50대', '60대 이상')
		GROUP BY AGE_RANGE, LDGS_ADDR
		) AS RANKED
WHERE ROW_NUM <= 5;